<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_61e849c972d13',
		'title' => 'Block: Sponsors',
		'fields' => array(
			array(
				'key' => 'field_61e8674dd2fd4',
				'label' => 'Section Heading',
				'name' => 'section_heading',
				'type' => 'text',
				'instructions' => 'Optional',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61e85e01d2fd1',
				'label' => 'Featured Sponsors Subheading',
				'name' => 'featured_sponsors_subheading',
				'type' => 'text',
				'instructions' => 'Optional',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61e849e7b394a',
							'operator' => '==',
							'value' => 'all_featured_first',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61e85e1cd2fd2',
				'label' => 'Sponsors Subheading',
				'name' => 'additional_sponsors_subheading',
				'type' => 'text',
				'instructions' => 'Optional',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61e849e7b394a',
							'operator' => '==',
							'value' => 'all_featured_first',
						),
					),
					array(
						array(
							'field' => 'field_61e849e7b394a',
							'operator' => '==',
							'value' => 'date',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61e849e7b394a',
				'label' => 'Display',
				'name' => 'display',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'date' => 'All Sponsors - Chronological (By date, newest first)(default)',
					'choose' => 'Choose Sponsors Manually',
					'featured' => 'Featured - Automatic (Show all the currently Featured Sponsors)',
					'all_featured_first' => 'All Active - Automatic (Featured First & Alphabetical)',
				),
				'default_value' => 'date',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_61f967e22c120',
				'label' => 'Columns',
				'name' => 'columns',
				'type' => 'select',
				'instructions' => 'Maximum number to show per row on larger screens',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => '1',
					2 => '2',
					3 => '3',
					4 => '4',
				),
				'default_value' => 3,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_61e84e40b394b',
				'label' => 'Sponsors List',
				'name' => 'sponsors_list',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61e849e7b394a',
							'operator' => '==',
							'value' => 'choose',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'sponsors',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'object',
				'ui' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/sponsors',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_61794dd8f32a2',
		'title' => 'Sponsor Meta Data',
		'fields' => array(
			array(
				'key' => 'field_61794ddd47f16',
				'label' => 'How To Use',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'The *Post Title* above is what you\'ll see in all dropdown menu selectors. The *Post Title* is NEVER USED on the frontend of the site, so you can make it as specific as you want. Then, fill out the fields below which will be used to create sponsorship pods across the site.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_61794e1047f17',
				'label' => 'Name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61ddca87de19f',
				'label' => 'Active',
				'name' => 'active',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'Show',
				'ui_off_text' => 'Hide',
			),
			array(
				'key' => 'field_61e84935912e4',
				'label' => 'Featured ✅',
				'name' => 'featured',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61ddca87de19f',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
			),
			array(
				'key' => 'field_61794e1647f18',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61794e2b47f19',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61794e3247f1a',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'sponsors',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	endif;